const PRODUCT_IMAGES = {
    'pro-1' : require('../public/images/products/1.jpg').default,
    'pro-2' : require('../public/images/products/2.png').default,
    'pro-3' : require('../public/images/products/3.png').default,
    'pro-4' : require('../public/images/products/4.png').default,
    'pro-5' : require('../public/images/products/5.png').default,
    'pro-6' : require('../public/images/products/6.png').default,
    'pro-7' : require('../public/images/products/7.png').default,
    'pro-8' : require('../public/images/products/8.png').default,
    'pro-9' : require('../public/images/products/9.png').default,
    'pro-10' : require('../public/images/products/10.png').default,
    'pro-11' : require('../public/images/products/11.png').default,
    'pro-12' : require('../public/images/products/12.png').default,
    'pro-13' : require('../public/images/products/13.png').default,
    'pro-14' : require('../public/images/products/14.jpg').default,
    'pro-15' : require('../public/images/products/15.jpg').default,
    'pro-16' : require('../public/images/products/16.jpg').default,
    'pro-17' : require('../public/images/products/17.jpg').default,
    'pro-18' : require('../public/images/products/18.jpg').default,
    'pro-19' : require('../public/images/products/19.jpg').default,
    'pro-20' : require('../public/images/products/20.jpg').default,
    'pro-21' : require('../public/images/products/21.jpg').default,
    'pro-22' : require('../public/images/products/22.jpg').default,
    'pro-23' : require('../public/images/products/23.png').default,
    'pro-24' : require('../public/images/products/24.jpg').default,
    'pro-25' : require('../public/images/products/25.jpg').default,
    'pro-26' : require('../public/images/products/26.jpg').default,
    'pro-27' : require('../public/images/products/27.png').default,
    'pro-28' : require('../public/images/products/28.jpg').default,

}

export default PRODUCT_IMAGES